using LiquidTodo.Core;

namespace LiquidTodo.Windows.Tests;

public sealed class TodoStoreTests : IDisposable
{
    private readonly string _root = Path.Combine(Path.GetTempPath(), "LiquidTodoWindowsTests", Guid.NewGuid().ToString("N"));
    private TodoStore Store(string name = "data.json") => new(new PersistenceService(Path.Combine(_root, name)));
    public TodoStoreTests() => Directory.CreateDirectory(_root);
    public void Dispose() { try { Directory.Delete(_root, true); } catch { } }

    [Fact] public void Add_rejects_blank_and_trims_text() { var store = Store(); Assert.Throws<ArgumentException>(() => store.Add(" \n")); var item = store.Add("  第一项  "); Assert.Equal("第一项", item.Text); }
    [Fact] public void Add_sorts_urgent_important_normal() { var store = Store(); store.Add("普通"); store.Add("重要", TodoPriority.Important); store.Add("紧急", TodoPriority.Urgent); Assert.Equal(["紧急", "重要", "普通"], store.Items.Select(x => x.Text)); }
    [Fact] public void Update_changes_text_priority_and_schedule() { var store = Store(); var item = store.Add("旧"); var at = DateTimeOffset.Now.AddDays(2); store.Update(item.Id, "新", TodoPriority.Urgent, new(TodoTimeMode.Deadline, at, ReminderMode: TodoReminderMode.AtTime)); Assert.Equal("新", store.Items[0].Text); Assert.Equal(TodoPriority.Urgent, store.Items[0].Priority); Assert.Equal(at, store.Items[0].Schedule!.Date); }
    [Fact] public void Move_persists_user_order() { var store = Store(); var a = store.Add("a"); store.Add("b"); store.Move(a.Id, 1); Assert.Equal(["b", "a"], Store().Items.Select(x => x.Text)); }
    [Fact] public void Completion_supports_undo_archive_restore_and_clear() { var store = Store(); var item = store.Add("a"); store.Complete(item.Id); Assert.True(store.Items.Single().Completed); store.UndoCompletion(item.Id); Assert.False(store.Items.Single().Completed); store.Complete(item.Id); store.ArchiveCompleted(item.Id); Assert.Empty(store.Items); Assert.Single(store.Archived); store.RestoreArchived(item.Id); Assert.Single(store.Items); store.ClearArchived(); Assert.Empty(store.Archived); }
    [Fact] public void Deadline_reminder_is_created_and_cancel_identifiers_are_stable() { var item = TodoItem.Create("提醒", schedule: new(TodoTimeMode.Deadline, DateTimeOffset.Now.AddHours(2), ReminderMode: TodoReminderMode.AtTime)); var request = Assert.Single(ReminderEngine.GetRequests(item, DateTimeOffset.Now)); Assert.Equal(item.Id, request.TodoId); Assert.Contains(item.Id.ToString(), ReminderEngine.AllIdentifiers(item)); }
    [Fact] public void Day_before_defaults_to_21_and_is_previous_day() { var local = DateTimeOffset.Now.Date.AddDays(3).AddHours(10); var item = TodoItem.Create("前一天", schedule: new(TodoTimeMode.Day, new DateTimeOffset(local), ReminderMode: TodoReminderMode.DayBefore, ReminderTimeMinutes: 1260)); var reminder = Assert.Single(ReminderEngine.GetRequests(item, DateTimeOffset.Now)); Assert.Equal(21, reminder.At.LocalDateTime.Hour); Assert.Equal(item.Schedule!.Date!.Value.LocalDateTime.Date.AddDays(-1), reminder.At.LocalDateTime.Date); }
    [Fact] public void Period_reminds_each_day_within_range() { var start = DateOnly.FromDateTime(DateTime.Today.AddDays(2)); var item = TodoItem.Create("期间", schedule: new(TodoTimeMode.Period, StartDate: start, EndDate: start.AddDays(2), ReminderMode: TodoReminderMode.DailyDuringPeriod, ReminderTimeMinutes: 9 * 60)); var all = ReminderEngine.GetRequests(item, DateTimeOffset.Now); Assert.Equal(3, all.Count); Assert.All(all, x => Assert.Equal(9, x.At.LocalDateTime.Hour)); }
    [Fact] public void Period_is_normalized_when_dates_reversed() { var end = DateOnly.FromDateTime(DateTime.Today); var schedule = new TodoSchedule(TodoTimeMode.Period, StartDate: end.AddDays(3), EndDate: end, ReminderMode: TodoReminderMode.DailyDuringPeriod).Normalize(); Assert.Equal(end, schedule.StartDate); Assert.Equal(end.AddDays(3), schedule.EndDate); }
    [Fact] public void Backup_round_trip_preserves_uuid_and_data() { var store = Store(); var item = store.Add("导出", TodoPriority.Important); var export = Path.Combine(_root, "backup.json"); store.Export(export); var other = Store("other.json"); var result = other.Import(export, ImportMode.Merge); Assert.Equal(1, result.ImportedItems); Assert.Equal(item.Id, other.Items.Single().Id); Assert.True(File.Exists(result.SafetyBackupPath)); }
    [Fact] public void Backup_merge_skips_matching_uuid() { var store = Store(); store.Add("同一项"); var export = Path.Combine(_root, "backup.json"); store.Export(export); var result = store.Import(export, ImportMode.Merge); Assert.Equal(1, result.SkippedDuplicates); Assert.Single(store.Items); }
    [Fact] public void Backup_replace_replaces_existing_data() { var first = Store(); first.Add("本机"); var second = Store("source.json"); second.Add("远端"); var backup = Path.Combine(_root, "source-backup.json"); second.Export(backup); first.Import(backup, ImportMode.Replace); Assert.Equal("远端", first.Items.Single().Text); }
    [Fact] public void Legacy_mac_reference_dates_migrate() { var fixture = Path.Combine(AppContext.BaseDirectory, "Fixtures", "mac-legacy-data.fixture.json"); var backup = new BackupService().Read(fixture); var item = Assert.Single(backup.Items); Assert.Equal("旧 Mac 待办", item.Text); Assert.Equal(TodoPriority.Important, item.Priority); Assert.Equal(TodoTimeMode.Deadline, item.Schedule!.Mode); Assert.Equal(new DateTimeOffset(2001, 1, 2, 0, 0, 0, TimeSpan.Zero), item.CreatedAt); }
    [Fact] public void Atomic_save_leaves_no_tmp_file() { var path = Path.Combine(_root, "atomic.json"); var store = new TodoStore(new PersistenceService(path)); store.Add("原子"); Assert.True(File.Exists(path)); Assert.False(File.Exists(path + ".tmp")); }
    [Fact] public void Corrupt_data_is_isolated_without_crash() { var path = Path.Combine(_root, "bad.json"); File.WriteAllText(path, "{"); var persistence = new PersistenceService(path); var store = new TodoStore(persistence); Assert.Empty(store.Items); Assert.NotNull(persistence.RecoveredCorruptFile); Assert.True(File.Exists(persistence.RecoveredCorruptFile)); }
    [Fact] public void Portable_and_installed_paths_are_isolated() { var exe = Path.Combine(_root, "exe"); Directory.CreateDirectory(exe); File.WriteAllText(Path.Combine(exe, "portable.flag"), ""); var portable = LiquidTodoPaths.Resolve([], exe, Path.Combine(_root, "local")); var installed = LiquidTodoPaths.Resolve([], Path.Combine(_root, "installed"), Path.Combine(_root, "local")); Assert.True(portable.IsPortable); Assert.False(installed.IsPortable); Assert.NotEqual(portable.DataFile, installed.DataFile); }
    [Fact] public void Explicit_portable_argument_overrides_without_flag() { var paths = LiquidTodoPaths.Resolve(["--portable"], Path.Combine(_root, "exe"), Path.Combine(_root, "local")); Assert.True(paths.IsPortable); Assert.Contains("Data", paths.DataFile); }
    [Fact] public void Snap_uses_nearest_edge_and_clamps_to_work_area() { var left = WindowSnapService.SnapToNearestEdge(new(40, -20, 48, 48), new(0, 0, 1920, 1040)); var right = WindowSnapService.SnapToNearestEdge(new(1800, 1100, 48, 48), new(0, 0, 1920, 1040)); Assert.Equal(7, left.X); Assert.Equal(7, left.Y); Assert.Equal(1865, right.X); Assert.Equal(985, right.Y); }
    [Fact] public void Snap_handles_second_monitor_negative_coordinates() { var snap = WindowSnapService.SnapToNearestEdge(new(-2500, 700, 48, 48), new(-2560, 0, 2560, 1440)); Assert.Equal(-2553, snap.X); Assert.InRange(snap.Y, 7, 1385); }
}
